services:
  nginx:
      image: nginx:alpine
      ports:
        - "8080:8080"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - triton
        - match_items
      networks:
        - app-network

  triton:
    container_name: triton
    image: nvcr.io/nvidia/tritonserver:24.09-py3
    ports:
      - 7000:7000  # HTTP 
      - 7001:7001  # GRPC 
      - 7002:7002  # Metrics 
    restart: always
    volumes:
      - ./app/triton/models:/models
    networks:
      - app-network
    command: [
      "tritonserver",
      "--model-repository=/models",
      "--http-port=7000",
      "--grpc-port=7001",
      "--metrics-port=7002"
    ]

  match_items:
    build: ./app/match_items
    expose: 
      - "5020"
    networks:
      - app-network
    depends_on:
      - triton 
    environment:
      - TRITON_SERVER_URL=triton:7001
  
  process_file:
    build: ./app/process_file
    expose: 
      - "5010"
    networks:
      - app-network
    depends_on:
      - triton 
      - match_items

networks:
  app-network:
    driver: bridge